server:
  port: 8081
  servlet:
    context-path: /agent/v1.0/kafka

spring:
  application:
    name: kafka-agent
  #修复3.0swagger问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
kafka:
  server: ${KAFKA_BROKER:10.255.65.212:9095,10.255.65.211:9095,10.255.65.210:9095}
  acl-enable: ${ACL_ENABLE:false}
  super-user: ${SUPER_USER:admin}
  super-user-pass: ${SUPER_USER_PASS:admin@12345}
  ssl-enable: ${SSL_ENABLE:false}
  tls-client:
      keystore: ${TLS_KEYSTORE_PATH:/opt/secrets/keystore/kafka.keystore.jks}
      truststore: ${TLS_TRUSTSTORE_PATH:/opt/secrets/truststore/kafka.truststore.jks}
      keystore-password: ${TLS_KEYSTORE_PASSWORD:111111}
      truststore-password: ${TLS_TRUSTSTORE_PASSWORD:111111}
